#!/usr/bin/env bash
# Install and configure HAproxy.

apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

echo '
frontend g3rm4n.tech
    bind 0:80
    default_backend web_server

backend web_server
    balance roundrobin
    server 461156-web-01 52.87.19.225:80 check
    server 461156-web-02 54.160.68.241:80 check
' >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
