#!/usr/bin/env bash
# Modify Nginx server's default HTTP port from 8080 to 80 by replacing the symbolic link in sites-enabled.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
