#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code and displays the data

FILE="apache-access.log"

awk '
{
    occurrences[$1" "$9]++
}

END {
    for (combination in occurrences) {
        split(combination, fields, " ")
        print occurrences[combination], fields[1], fields[2]
    }
}
' "$FILE" | sort -rn
