#!/usr/bin/env bash
# Script that configures the container so that nginx runs as nginx user,
# and listens on all active IPs on port 8080.
pkill apache2
sed -i 's/user\s*\(.*\);/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chmod 644 /etc/nginx/sites-available/default
sudo -u nginx service nginx start
